config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get "/", to: redirect('/fr', status:301)
  # Defines the root path route ("/")
  # root "posts#index"

  scope "/backoff" do
    #get "/", to: "admin#home"
    resources :admins, only: [:index], path:"/"
    resources :actifs, only: [:new,:create,:edit,:update,:destroy], as: :actif_backoff
    get "actifs", to: "admins#actifs", as: :actifs_backoff
    resources :articles, only: [:new,:create,:edit,:update,:destroy]
    resources :prestations, only: [:new, :create,:edit,:update,:destroy]
    resources :faqs, except:[:index],path: :faq
  end

  scope "/:locale" do
    root "pages#home"
    get "about", to: "pages#about"
    resources :actifs, only:[:index,:show]
    resources :authors,path:"/experts"
    get "blog", to: "articles#index"
    get "blog/:id", to: "articles#show", as: :post
    get "blog/:slug_authors/:id", to: "articles#show", as: :post_author
    get "blog/:category", to: "articles#category", as: :blog_category
    post "blog/category_filter", to: "articles#category_filter", as: :blog_filter
    get "prestation/:id",to: "prestations#show", as: :prestation_show

     post "send", to: "pages#send_contact"

    #get "/actifs", controller: "actifs", action: "index"
    #get "/actifs/:id", controller: "actifs", action: "show"
    localized do
      get "laboratoire-plantes", to: "pages#laboratoire_plantes"
      get "analyse-recherche-developpement",to: "pages#analyses"
      get "laboratoire-cosmetologie",to: "pages#cosmetologie"
      get "actifs",to: "actifs#index",as: :actifs
      get "faqs",to: "faqs#index",as: :faqs
      get "authors",to: "authors#index",as: :authors
      get "contact",to: "pages#contact"
      #resources :actifs, only:[:index,:show]
    end
  end




end

app/models/article.rb
class Article < ApplicationRecord
  has_many :author_publications
  has_many :authors, through: :author_publications
  has_many :category_articles
  has_many :categories, through: :category_articles
  has_rich_text :intro
  has_richer_text :content, store_as: :json

  has_one_attached :cover

  #validates :authors, presence: true
  validates :lang, presence: true

  extend FriendlyId
  friendly_id :titre, use: :slugged

  after_validation :slug_authors, on: [ :create, :update ]

  paginates_per 8

  def slug_authors
    slug = []
    self.authors.each do |author|
      slug << "#{author.firstname.downcase }-#{author.lastname.downcase}"
    end
    self.slug_authors = slug.join("-")
  end
  def reading_time(text)
    word_count = text.split.size
    words_per_minute = 150
    (word_count.to_f / words_per_minute.to_f).ceil()
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_categories
  def index
    #@articles = Article.where(lang:params[:locale])
    if !params[:page].present?
      @headline = Article.where(headline:true).first
    end

    @articles = Article.where(lang:params[:locale]).order(:titre).page params[:page]

    add_breadcrumb "Blog", :blog_path
  end

  def show
    @article = Article.friendly.find(params[:id])

    headings = JSON.parse(@article.content.body)["content"].select{|arr| arr["type"] === "heading"}
    headings_2 = headings.select{|arr| arr["attrs"]["level"] === 2}

    @summary = []

    headings_2.each_with_index do |head, index|
      head["attrs"].merge!(id:index) if !head["content"].nil?
      @summary << {head: head["content"][0]["text"], index: index} if !head["content"].nil?
    end

    add_breadcrumb "Blog", :blog_path
    add_breadcrumb "<span>#{@article.titre}</span>".html_safe
  end

  def new
    @article = Article.new
    @authors = Author.all
  end

  def create
    #require 'json'
    @article = Article.new(article_params)
    @authors = params[:article][:author_ids].reject { |c| c.empty? }
    @authors = Author.where(id:@authors)
    @article.authors = @authors
    @article.save

    redirect_to blog_path
  end

  def edit
    @article = Article.friendly.find(params[:id])
  end

  def update
    @article = Article.friendly.find(params[:id])
    @article.update(article_params)
    authors = params[:article][:author_ids].reject { |c| c.empty? }
    @authors = Author.where(id:authors)
    @article.authors = @authors

    #xx = ((JSON.parse(@article.content.body)["content"].select{|arr| arr["type"] === "heading"}).select{|arr| arr["attrs"]["level"] === 2}).each_with_index do |head, index|
      #head["attrs"].merge!(id:index) if !head["content"].nil?
    #end

    #counter_ids = 0
    #yy = JSON.parse(@article.content.body)
    #yy["content"].each do |arr|
    #  if arr["type"] === "heading" && arr["attrs"]["level"] === 2
    #    arr["attrs"].merge!("id": counter_ids)
    #    counter_ids += 1
    #  end
    #end

    #@article.content.body = yy.to_json
    #zz = JSON.parse(@article.content.body)
    #@article.content.body = yy.to_json

    categories = params[:article][:category_ids].reject { |c| c.empty? }
    @categories = Category.where(id:categories)
    @article.categories = @categories

    @article.save!

    redirect_to blog_path
  end

  def destroy
  end

  def category
    fail
  end
  def category_filter
    category = params[:cat].downcase
    if !category.blank?
      @articles = Category.find_by(titre:params[:cat].downcase).articles.where(lang:params[:locale])

      articles_filtered = []
      @articles.each do |article|
        articles_filtered << article if article.categories.first.titre == params[:cat].downcase
      end

      @articles = Article.where(id: articles_filtered.map(&:id))
    else
      @articles = Article.where(lang: params[:locale])
    end

    @headline = Article.where(headline:true).first

    respond_to do |format|
      format.turbo_stream { render 'category_filter', locals: { articles: @articles,category: category,headline:@headline }}
      format.html { redirect_to blog_category_path(category)}
    end
  end
  private
  def article_params
    params.require(:article).permit(:titre,:content,:slug_authors,:slug,:lang,:title,:meta_description,:indexed,:follow,:intro,:read_time,:cover,:legend_cover,:headline,:summary,categories:[])
  end

  def set_categories
    @categories = []
    Category.all.each do |cat|
      @categories.push(cat) if cat.articles_size(params[:locale]) > 0
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles_list.html.erb
<ul id="liste_blog" class="inside">
    <% if category == "" %>
      <% if @headline.present? %>
        <% if @headline.cover.attached? %>
          <li class="cover_blog" style="background-image: url(<%= rails_blob_url(@headline.cover) %>)" %>
        <% else %>
          <li class="cover_blog" %>
        <% end %>
          <% if @headline.slug_authors.present? && !@headline.slug_authors.empty?%>
            <%= link_to post_author_path(@headline.slug_authors,@headline) do %>
              <div id="headline_cover">
                <h3 id="headline_titre_cover"><%= t('blog.breaking_news')%></h3>
                <span class="blog_cover_strike"></span>
              </div>
              <div class="cover_blog_article_headline">
                <div>
                  <span class="tag_cat"><%= @headline.categories.first.titre if @headline.categories.present? %></span>
                  <h2><%= @headline.titre %></h2>
                </div>
                <div class="card_blog_metadonnes">
                 <p>Publié le <%= l @headline.created_at, format: :short %></p>
                  <p>Temps de lecture : <%= image_tag "pictos/chrono.svg" %><%= @headline.reading_time(@headline.content.to_plain_text) %> min</p>
                </div>
              </div>
            <% end %>
          <% else %>
            <%= link_to post_path(@headline) do %>
              <div id="headline_cover">
                <h3 id="headline_titre_cover"><%= t('blog.breaking_news')%></h3>
                <span class="blog_cover_strike"></span>
              </div>
              <div class="cover_blog_article_headline">
                <div>
                  <span class="tag_cat"><%= @headline.categories.present? %></span>
                  <h2><%= @headline.titre %></h2>
                </div>
                <div class="card_blog_metadonnes">
                  <p>Publié le <%= l @headline.created_at, format: :short %></p>
                <p>Temps de lecture : <%= image_tag "pictos/chrono.svg" %><%= article.reading_time(article.content.to_plain_text) %> min</p>
                </div>
              </div>
            <% end %>
          <% end %>
        </li>
      <% end %>
    <% end %>
    <% @articles.each do |article| %>
    <li class="card_blog">
    <% if article.slug_authors.present? && !article.slug_authors.empty? %>
      <%= link_to post_author_path(article.slug_authors,article) do %>
        <% if article.cover.attached? %>
          <div class="card_blog_img">
            <%= image_tag article.cover %>
          </div>
        <% end %>
        <div class="card_blog_content">
          <div class="card_blog_cat">
            <span class="tag_cat"><%= article.categories.first.titre if !article.categories.empty? %></span>
          </div>
          <h2 class="card_blog_titre">
            <%= article.titre %>
          </h2>
          <p class="card_blog_summary">
            <%= article.intro.to_plain_text.truncate(200, omission: '') %>
          </p>
        </div>
        <div class="card_blog_metadonnes">
          <p>Publié le <%= l article.created_at, format: :short %></p>
          <p>Temps de lecture : <%= image_tag "pictos/chrono.svg" %><%= article.reading_time(article.content.to_plain_text) %> min</p>
        </div>
      <% end %>
    <% else %>
      <%= link_to post_path(article) do %>
        <% if article.cover.attached? %>
          <div class="card_blog_img">
            <%= image_tag article.cover %>
          </div>
        <% end %>
        <div class="card_blog_content">
          <div class="card_blog_cat">
            <span class="tag_cat"><%= article.categories.first.titre if !article.categories.empty? %></span>
          </div>
          <h2 class="card_blog_titre">
            <%= article.titre %>
          </h2>
          <p class="card_blog_summary">
            <%= article.intro.to_plain_text.truncate(200, omission: '') %>
          </p>
        </div>
        <div class="card_blog_metadonnes">
          <p>Publié le <%= l article.created_at, format: :short %></p>
          <p>Temps de lecture : <%= image_tag "pictos/chrono.svg" %><%= article.reading_time(article.content.to_plain_text) %> min</p>
        </div>
      <% end %>
    <% end %>
    </li>
    <% end %>
  </ul>

app/views/articles/_filters_list_blog.html.erb
<ul id="filters_list_blog">
    <%= link_to "Tous", blog_path(),class:"tag_filter" %>
    <% @categories.each do |cat_filter| %>
      <% if cat_filter.titre.downcase == category %>
        <%= button_to cat_filter.titre,blog_filter_path(cat:cat_filter.titre.downcase),class:"tag_filter active" %>
      <% else %>
        <%= button_to cat_filter.titre,blog_filter_path(cat:cat_filter.titre.downcase),class:"tag_filter" %>
      <% end %>
    <% end %>
</ul>

app/views/articles/category.html.erb
<h1>Category</h1>

app/views/articles/category_filter.html.erb
<% fail %>

app/views/articles/category_filter.turbo_stream.erb
<%= turbo_stream.replace "liste_blog" do %>
	<%= render partial: "articles_list", locals: { articles: articles, category: category } %>
<% end %>


<%= turbo_stream.replace "filters_list_blog" do %>
	<%= render partial: "filters_list_blog", locals: { category: category } %>
<% end %>

app/views/articles/create.html.erb
<h1>Articles#create</h1>
<p>Find me in app/views/articles/create.html.erb</p>

app/views/articles/destroy.html.erb
<h1>Articles#destroy</h1>
<p>Find me in app/views/articles/destroy.html.erb</p>

app/views/articles/edit.html.erb
<h1>Articles#edit</h1>
<p>Find me in app/views/articles/edit.html.erb</p>
<div class="inside" style="padding-top:10em;">
<%= simple_form_for @article do |f| %>
  <%= f.association :authors, collection: Author.all,
      value_method: :id, label_method: :lastname,
      as: :check_boxes, include_blank: false %>
  <!--
  <%= f.simple_fields_for :author do |p| %>
    <%= p.input :author_ids, as: :check_boxes, collection: Author.all.map {|f| ["#{f.lastname} #{f.firstname}",f.id]} %>
  <% end %>
  -->
<%= f.input :lang, collection:["fr","en","de","es"] %>
 <%= f.association :categories, collection: Category.all,
      value_method: :id, label_method: :titre,
      as: :check_boxes, include_blank: false %>
<%= f.input :titre %>
<%= f.rich_text_area :intro %>
<%= f.input :slug %>
<%= f.input :summary,label:"inclure une table des matières"%>
<%= f.input :headline,label:"Mettre l'article 'À la une'"%>
<div>
<%= f.label :content %>
<%= f.richer_text_area :content,tables:true,callouts:true %>
</div>
<%= f.file_field :cover %>
<%= f.input :legend_cover %>
<%= f.button :submit,class:"button" %>
<% end %>
</div>

app/views/articles/index.html.erb
<div id="landing_header">
  <div class="landing_header_content" id="blog_header">
      <h1>Blog</h1>
      <nav>
      <ul id="filters_list_blog">
      <%= link_to "Tous", blog_path(),class:"tag_filter active" %>
        <% @categories.each do |cat_filter| %>
          <%= button_to cat_filter.titre,blog_filter_path(cat:cat_filter.titre.downcase),class:"tag_filter" %>
        <% end %>
      </ul>
      </nav>
  </div>
</div>
<div data-controller="blog">

  <ul id="liste_blog" class="inside">
    <% if @headline.present? %>
      <% if @headline.cover.attached? %>
        <li class="cover_blog" style="background-image: url(<%= rails_blob_url(@headline.cover) %>)" %>
      <% else %>
        <li class="cover_blog" %>
      <% end %>
        <% if @headline.slug_authors.present? && !@headline.slug_authors.empty?%>
           <%= link_to post_author_path(@headline.slug_authors,@headline) do %>
            <div id="headline_cover">
              <h3 id="headline_titre_cover"><%= t('blog.breaking_news')%></h3>
              <span class="blog_cover_strike"></span>
            </div>
            <div class="cover_blog_article_headline">
              <div>
                <span class="tag_cat"><%= @headline.categories.first.titre if @headline.categories.present? %></span>
                <h2><%= @headline.titre %></h2>
              </div>
              <div class="card_blog_metadonnes">
                <p>Publié le <%= l @headline.created_at, format: :short %></p>
                <p>Temps de lecture : <%= image_tag "pictos/chrono.svg" %><%= @headline.reading_time(@headline.content.to_plain_text) %> min</p>
              </div>
            </div>
          <% end %>
        <% else %>
          <%= link_to post_path(@headline) do %>
            <div id="headline_cover">
              <h3 id="headline_titre_cover"><%= t('blog.breaking_news')%></h3>
              <span class="blog_cover_strike"></span>
            </div>
            <div class="cover_blog_article_headline">
              <div>
                <span class="tag_cat"><%= @headline.categories.first.titre if @headline.categories.present? %></span>
                <h2><%= @headline.titre %></h2>
              </div>
              <div class="card_blog_metadonnes">
                <p>Publié le <%= l @headline.created_at, format: :short %></p>
                <p>Temps de lecture : <%= image_tag "pictos/chrono.svg" %><%= @headline.reading_time(@headline.content.to_plain_text) %> min</p>
              </div>
            </div>
          <% end %>
        <% end %>
      </li>
    <% end %>
    <% @articles.each do |article| %>
    <li class="card_blog">
    <% if article.slug_authors.present? && !article.slug_authors.empty? %>
      <%= link_to post_author_path(article.slug_authors,article) do %>
        <% if article.cover.attached? %>
          <div class="card_blog_img">
            <%= image_tag article.cover %>
          </div>
        <% end %>
        <div class="card_blog_content">
          <div class="card_blog_cat">
            <span class="tag_cat"><%= article.categories.first.titre if !article.categories.empty? %></span>
          </div>
          <h2 class="card_blog_titre">
            <%= article.titre %>
          </h2>
          <p class="card_blog_summary">
            <%= article.intro.to_plain_text.truncate(200, omission: '') %>
          </p>
        </div>
        <div class="card_blog_metadonnes">
          <p>Publié le <%= l article.created_at, format: :short %></p>
          <p>Temps de lecture : <%= image_tag "pictos/chrono.svg" %><%= article.reading_time(article.content.to_plain_text) %> min</p>
        </div>
      <% end %>
    <% else %>
      <%= link_to post_path(article) do %>
        <% if article.cover.attached? %>
          <div class="card_blog_img">
            <%= image_tag article.cover %>
          </div>
        <% end %>
        <div class="card_blog_content">
          <div class="card_blog_cat">
            <span class="tag_cat"><%= article.categories.first.titre if !article.categories.empty? %></span>
          </div>
          <h2 class="card_blog_titre">
            <%= article.titre %>
          </h2>
          <p class="card_blog_summary">
            <%= article.intro.to_plain_text.truncate(200, omission: '') %>
          </p>
        </div>
        <div class="card_blog_metadonnes">
          <p>Publié le <%= l article.created_at, format: :short %></p>
          <p>Temps de lecture : <%= image_tag "pictos/chrono.svg" %><%= article.reading_time(article.content.to_plain_text) %> min</p>
        </div>
      <% end %>
    <% end %>
    </li>
    <% end %>
  </ul>
    <!--
    <div class="card_prestation_displayed">
      <div class="card_prestation_text">
        <h3>Vous recherchez à doser certaines substances ou molécules dans diverses matrices de plante ?</h3>
        <p>Nos experts sont capables d'identifier une large diversité de familles de molécules via de nombreuses méthodes de dosages complexes pour identifier et quantifier les composés actifs des plantes, pour les valoriser ou réduire les risques associés</p>
        <%= link_to "En savoir plus", "",class:"btn_contact"%>
      </div>
      <div class="card_prestation_cover">
        <%= image_tag "" %>
      </div>
    </div>
    -->
</div>
<ul>
<% @articles.each do |article| %>
<li><%= link_to article.titre, post_path(article) %> | <%= link_to "edit", edit_article_path(article) %>
</li>
<% end %>
</ul>

<%= paginate @articles %>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>
<div class="inside" style="padding-top:10em;">
<%= simple_form_for @article do |f| %>
  <%= f.association :authors, collection: Author.all,
      value_method: :id, label_method: :lastname,
      as: :check_boxes, include_blank: false %>
  <%= f.input :lang, collection:["fr","en","de","es"], selected:0 %>
<div class="form_seo">
<%= f.input :title %>
<%= f.input :meta_description %>
<%= f.input :indexed %>
<%= f.input :public %>
<%= f.input :summary %>
</div>
<%= f.input :titre %>
<%= f.rich_text_area :intro %>
<div>
<%= f.label :content %>
<%= f.richer_text_area :content,tables:true,callouts:true, :input_html => { 'rows' => 10} %>
</div>
<%= f.file_field :cover %>
<%= f.input :legend_cover %>
<%= f.button :submit,class:"button" %>
<% end %>
</div>

app/views/articles/show.html.erb
<article id="blog_article" data-controller="blog">
  <div id="post_header">
    <div id="post_header_intro">
      <span class="line_green"></span>
      <div>
        <h1><%= @article.titre %></h1>
        <div class="post_tags">
          <% @article.categories.each do |cat| %>
            <span class="tag_cat"><%= cat.titre.capitalize %></span>
          <% end %>
        </div>
        <p><%= @article.intro %></p>
        <div class="post_header_author">
          <% @article.authors.each do |author| %>
            <div class="author_detail_article">
            <div class="img_author_detail_article">
              <% if author.avatar.attached? %>
                <%= image_tag author.avatar, width:"64" if author.avatar.attached? %>
              <% else %>
                <img src="" alt="">
              <% end %>
            </div>
            <div>
              <p><%= link_to author_path(author) do %>
              <%= author.firstname%> <%= author.lastname %>
              <% end %>
              </p>
              <p><%= author.function %></p>
            </div>
            </div>
          <% end %>
        </div>
        <div class="post_header_date_time">
          <div>
            <p>Publié le <b><%= l @article.created_at, format: :short %></b></p>
            <span>-</span>
            <p>Mis à jour le: <b><%= l @article.created_at, format: :short %></b></p>
          </div>
          <p>Temps de lecture : <%= image_tag "pictos/chrono.svg" %><b><%= @article.reading_time(@article.content.to_plain_text) %> min</b></p>
        </div>
      </div>
    </div>
  </div>
  <div id="blog_article" class="inside">
    <section class="article_cover">
      <div>
      <%= image_tag @article.cover if @article.cover.present? %>
      </div>
      <p class="article_cover_legend"><%= @article.legend_cover %></p>
    </section>
    <section class="blog_article_content">
      <div class="article_table_matieres" data-blog-target="summary">
        <% if @article.summary == true && !@summary.empty? %>
          <p class="article_table_matieres_titre"><%= t('blog.sur_cette_page') %> <%= image_tag "pictos/arrow-summary.svg"%></p>
          <nav>
            <ul>
              <% @summary.each do |hash| %>
                <li><a href="#<%=hash[:index]%>" data-action="click->blog#clickLinkSummary" data-blog-target="linkSummary" data-turbolinks="false"><%= hash[:head] %></a></li>
              <% end %>
            </ul>
          </nav>
        <% end %>
        <div class="share_article">
          <p><%= t('blog.partager_article')%> :</p>
          <div class="sharing_socials_icones blog">
            <a href=""><%= image_tag "pictos/share-contact/facebook.svg", width:"16", height:"16", alt:"" %></a>
            <a href=""><%= image_tag "pictos/share-contact/twitter.svg", width:"16", height:"16", alt:"" %></a>
            <a href=""><%= image_tag "pictos/share-contact/linkedin.svg", width:"16", height:"16", alt:"" %></a>
            <a href=""><%= image_tag "pictos/share-contact/mail.svg", width:"16", height:"16", alt:"" %></a>
          </div>
        </div>
      </div>
      <div class="blog_article_main_content" data-blog-target="mainContent">
        <%= @article.content %>
      </div>
    </section>
  </div>
</article>

app/views/articles/update.html.erb
<h1>Articles#update</h1>
<p>Find me in app/views/articles/update.html.erb</p>