config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get "/", to: redirect('/fr', status:301)
  # Defines the root path route ("/")
  # root "posts#index"

  scope "/backoff" do
    #get "/", to: "admin#home"
    resources :admins, only: [:index], path:"/"
    resources :actifs, only: [:new,:create,:edit,:update,:destroy], as: :actif_backoff
    get "actifs", to: "admins#actifs", as: :actifs_backoff
    resources :articles, only: [:new,:create,:edit,:update,:destroy]
    resources :prestations, only: [:new, :create,:edit,:update,:destroy]
    resources :faqs, except:[:index],path: :faq
  end

  scope "/:locale" do
    root "pages#home"
    get "about", to: "pages#about"
    resources :actifs, only:[:index,:show]
    resources :authors,path:"/experts"
    get "blog", to: "articles#index"
    get "blog/:id", to: "articles#show", as: :post
    get "blog/:slug_authors/:id", to: "articles#show", as: :post_author
    get "blog/:category", to: "articles#category", as: :blog_category
    post "blog/category_filter", to: "articles#category_filter", as: :blog_filter
    get "prestation/:id",to: "prestations#show", as: :prestation_show

     post "send", to: "pages#send_contact"

    #get "/actifs", controller: "actifs", action: "index"
    #get "/actifs/:id", controller: "actifs", action: "show"
    localized do
      get "laboratoire-plantes", to: "pages#laboratoire_plantes"
      get "analyse-recherche-developpement",to: "pages#analyses"
      get "laboratoire-cosmetologie",to: "pages#cosmetologie"
      get "actifs",to: "actifs#index",as: :actifs
      get "faqs",to: "faqs#index",as: :faqs
      get "authors",to: "authors#index",as: :authors
      get "contact",to: "pages#contact"
      #resources :actifs, only:[:index,:show]
    end
  end




end

app/models/actif.rb
class Actif < ApplicationRecord
  has_many_attached :photos
  has_one_attached :document
  TYPE_PRODUITS = ["cosmétique","nutraceutique"]
  PROPRIETES = ["minceur","brûle graisse"]
end

app/controllers/actifs_controller.rb
class ActifsController < ApplicationController
  layout "backoffice",only:[:new,:create,:edit,:update,:destroy]

  def index
    add_breadcrumb t("breadcrumbs.actifs") , :actifs_path
    lang = locale.to_s
    @actifs = Actif.where(lang: lang)
  end

  def new
    @actif = Actif.new
    @ingredients =  YAML.load_file("#{Rails.root.to_s}/db/ingredients.yml")["ingredients"]
  end

  def create
    @actif = Actif.new(actif_params)
    @actif.save
  end

  def show
    @actif = Actif.find(params[:id])
    @cats_produits = @actif.cat_produits.reject { |c| c.empty? }
    @props_actif = @actif.props_tags.reject { |c| c.empty? }
    @actifs = Actif.where(lang:params[:locale])
    add_breadcrumb t("breadcrumbs.actifs") , :actifs_path
    add_breadcrumb "<span>#{@actif.name}</span>".html_safe, :actif_path
  end

  def edit
    @actif = Actif.find(params[:id])
    @ingredients =  YAML.load_file("#{Rails.root.to_s}/db/ingredients.yml")["ingredients"]
  end

  def update
    @actif = Actif.find(params[:id])
    @actif.update(actif_params)
    redirect_to actifs_path
  end

  def destroy
  end

  private
  def actif_params
    params.require(:actif).permit(:lang,:name,:description,:proprietes,:types_produits,:cible,:efficacite,:donnees,:concentration,:document,photos: [],cat_produits:[],props_tags:[],composition:[])
  end

end

app/helpers/actifs_helper.rb
module ActifsHelper
end

app/views/actifs/create.html.erb
<h1>Actifs#create</h1>
<p>Find me in app/views/actifs/create.html.erb</p>

app/views/actifs/destroy.html.erb
<h1>Actifs#destroy</h1>
<p>Find me in app/views/actifs/destroy.html.erb</p>

app/views/actifs/edit.html.erb
<h1>Actifs#edit</h1>
<p>Find me in app/views/actifs/edit.html.erb</p>
<%= simple_form_for @actif,:url => actif_backoff_path, :method => :patch do |f| %>
  <%= f.input :lang, collection:["fr","en","de","es"] %>
  <%= f.input :name,label:"Nom de l'actif" %>
  <%= f.input :cat_produits, label:"Catégories de l'actif", collection:Actif::TYPE_PRODUITS, as: :check_boxes %>
  <%= f.input :props_tags, label:"Propriétés de l'actif",collection:Actif::PROPRIETES, as: :check_boxes%>
  <%= f.input :description,label:"Description courte de l'actif" %>
  <%= f.input :composition,label:"Composition INCI",collection:@ingredients,as: :check_boxes %>
  <%= f.input :proprietes,label:"Revendications et propriétés" %>
  <%= f.input :types_produits %>
  <%= f.input :cible, label:"Cible biologique innovante" %>
  <%= f.input :efficacite, label:"Efficacité in vitro" %>
  <%= f.input :donnees,label: "Données clinique/in vivo" %>
  <%= f.input :concentration, label:"Concentration dans la formule/ Dosage"%>
  <%= f.input :ecocert %>
  <%= f.input :made_in_france %>
  <hr>
  <p>PDF</p>
  <%= f.file_field :document %>
  <hr>
  <% @actif.photos.each do |image| %>
    <%= f.hidden_field :photos, multiple: true, value: image.signed_id %>
  <% end %>
  <%= f.file_field :photos, multiple: true %>
  <%= f.button :submit %>
<% end %>
<!--
,collection: Actif::TYPE_PRODUITS,as: :check_boxes
-->

app/views/actifs/index.html.erb
<article id="actifs_index">
  <div id="actifs_header">
    <div class="inside actifs_header_text">
      <h1 class=""><%= t("actifs.actifs_titre")%></h1>
      <p class="actifs_text_presentation">En 15 ans, nos chercheurs ont analysé plus de 2500 extraits de plantes. Nous avons sélectionné les meilleurs pour en tirer de puissantes molécules actives à intégrer dans vos produits
        <%= link_to "En savoir plus" %>
      </p>
    </div>
  </div>

  <div class="actifs_main">
    <ul id="actifs_list" class="inside">
    <div class="actifs_list_index">
      <p class="actifs_text_presentation">En 15 ans, nos chercheurs ont analysé plus de 2500 extraits de plantes. Nous avons sélectionné les meilleurs pour en tirer de puissantes molécules actives à intégrer dans vos produits.<%= link_to "En savoir plus" %></p>
    </div>
    <% @actifs.each do |actif| %>
      <li class="card_carousel">
          <%= link_to actif_path(actif) do %>
            <div class="card_carousel_img">
              <%= image_tag actif.photos[0] if actif.photos[0].present? %>
            </div>
            <div class="card_carousel_description">
              <span class="actif_property">Propriété</span>
              <h2 class="card_actif_titre"><%= actif.name %></h2>
              <div class="card_actif_text">
                <p>Ingrédient cosmétique minceur & raffermissant</p>
                <span class="card_actif_btn">Découvrir<%= image_tag 'arrow-right.svg'%></span>
              </div>
            </div>
          <% end %>
        </li>
    <% end %>
    <li class="card_carousel extraction">
      <div class="card_extraction_content">
        <%= image_tag "Logo-Phytodia-white.svg",width:"100px"%>
        <div class="card_extraction_text">
          <h2>Extraction<br> sur mesure</h2>
          <p>Vous souhaitez développer votre propre actif à partir d'une ressource naturelle ?</p>
        </div>
        <%= link_to "" do %>
          <span>En savoir plus</span><%= image_tag "arrow-right.svg"%>
        <% end %>
      </div>
    </li>
    </ul>
    <div class="inside actifs_description_page">
    <h2>Votre fournisseur d'ingrédients actifs pour vos cosmétiques et autres produits à base de plante</h2>
    <p>Ayant développé au cours des années un important réseau de fournisseurs de plantes et d'ingrédients, en privilégiant à chaque fois le meilleur des plantes, nous pouvons aujourd'hui vous proposer un ensemble d'extraits de plantes et d'ingrédients actifs pouvant entrer dans le développement et la composition de vos cosmétiques et de vos autres produits à base de plante.</p>
    </div>
  </div>
</article>

app/views/actifs/new.html.erb
<h1>Actifs#new</h1>
<p>Find me in app/views/actifs/new.html.erb</p>

<%= simple_form_for @actif,:url => actif_backoff_index_path, :method => :post do |f| %>
  <%= f.input :lang, collection:["fr","en","de","es"] %>
  <%= f.input :name,label:"Nom de l'actif" %>
  <%= f.input :cat_produits, label:"Catégories de l'actif", collection:Actif::TYPE_PRODUITS, as: :check_boxes %>
  <%= f.input :props_tags, label:"Propriétés de l'actif",collection:Actif::PROPRIETES, as: :check_boxes%>
  <%= f.input :description,label:"Description courte de l'actif" %>
  <%= f.input :composition,label:"Composition INCI" %>
  <%= f.input :proprietes,label:"Revendications et propriétés" %>
  <%= f.input :types_produits %>
  <%= f.input :cible, label:"Cible biologique innovante" %>
  <%= f.input :efficacite, label:"Efficacité in vitro" %>
  <%= f.input :donnees,label: "Données clinique/in vivo" %>
  <%= f.input :concentration, label:"Concentration dans la formule/ Dosage"%>
  <%= f.input :ecocert %>
  <%= f.input :made_in_france %>
  <% @actif.photos.each do |image| %>
    <%= f.hidden_field :photos, multiple: true, value: image.signed_id %>
  <% end %>
  <%= f.file_field :photos, multiple: true %>
  <%= f.button :submit %>
<% end %>

app/views/actifs/show.html.erb
<article class="">
<section class="inside actif_show">
  <div class="actifs_photos">
    <div class="first_actif_photo">
      <%= image_tag @actif.photos[0], crop: :fill if @actif.photos[0].present? %>
    </div>
    <div class="second_actif_photo">
      <div>
        <%= image_tag @actif.photos[0], crop: :fill if @actif.photos[0].present? %>
      </div>
      <div>
        <%= image_tag @actif.photos[0], crop: :fill if @actif.photos[0].present? %>
      </div>
    </div>
    <div class="actif_labels">
      <% if @actif.ecocert? %>
      <div>
        <%= image_tag "ecocert.svg" %>
      </div>
      <% end %>
      <% if @actif.made_in_france? %>
      <div>
        <%= image_tag "made-in-france.svg" %>
      </div>
      <% end %>
    </div>
  </div>
  <div class="actif_description">
    <h1 class="actif_titre"><%= @actif.name %></h1>
    <div class="properties_actif">
      <span class="actif_property"><%= @props_actif.join(', ')%></span>
    <% @cats_produits.each do |cat| %>
      <span class="actif_property"><%= cat %></span>
    <% end %>
    </div>
    <p class="actif_text_head"><%= @actif.description %></p>
    <div class="accordions_list" data-controller="accordeon">
      <div class="accordion">
        <div class="accordion_head" data-action="click->accordeon#toggleHorizontal" data-accorderon-target="horizontal">
          <h2 class="accordion_titre">Composition (INCI)</h2><span><%= image_tag "pictos/croix-black.svg",class:"croix visible"%><%= image_tag "pictos/moins-green.svg",class:"moins"%></span>
        </div>
        <div class="accordion_content">
          <p><%= @actif.composition %></p>
        </div>
      </div>

      <div class="accordion">
        <div class="accordion_head" data-action="click->accordeon#toggleHorizontal" data-accorderon-target="horizontal">
          <h2 class="accordion_titre">Revendications et propriétés</h2><span><%= image_tag "pictos/croix-black.svg",class:"croix visible"%><%= image_tag "pictos/moins-green.svg",class:"moins"%></span>
        </div>
        <div class="accordion_content">
        </div>
      </div>

      <div class="accordion">
        <div class="accordion_head" data-action="click->accordeon#toggleHorizontal" data-accorderon-target="horizontal">
          <h2 class="accordion_titre">Dans quels types de produits l'utiliser ?</h2><span><%= image_tag "pictos/croix-black.svg",class:"croix visible"%><%= image_tag "pictos/moins-green.svg",class:"moins"%></span>
        </div>
        <div class="accordion_content">
        </div>
      </div>

      <div class="accordion">
        <div class="accordion_head" data-action="click->accordeon#toggleHorizontal" data-accorderon-target="horizontal">
          <h2 class="accordion_titre">Cible biologique innovante</h2><span><%= image_tag "pictos/croix-black.svg",class:"croix visible"%><%= image_tag "pictos/moins-green.svg",class:"moins"%></span>
        </div>
        <div class="accordion_content">
        </div>
      </div>

      <div class="accordion">
        <div class="accordion_head" data-action="click->accordeon#toggleHorizontal" data-accorderon-target="horizontal">
          <h2 class="accordion_titre">Efficacité in vitro</h2><span><%= image_tag "pictos/croix-black.svg",class:"croix visible"%><%= image_tag "pictos/moins-green.svg",class:"moins"%></span>
        </div>
        <div class="accordion_content">
        </div>
      </div>

      <div class="accordion">
        <div class="accordion_head" data-action="click->accordeon#toggleHorizontal" data-accorderon-target="horizontal">
          <h2 class="accordion_titre">Données clinique/in vitro</h2><span><%= image_tag "pictos/croix-black.svg",class:"croix visible"%><%= image_tag "pictos/moins-green.svg",class:"moins"%></span>
        </div>
        <div class="accordion_content">
        </div>
      </div>

      <div class="accordion">
        <div class="accordion_head" data-action="click->accordeon#toggleHorizontal" data-accorderon-target="horizontal">
          <h2 class="accordion_titre">Concentration dans la formule/ Dosage</h2><span><%= image_tag "pictos/croix-black.svg",class:"croix visible"%><%= image_tag "pictos/moins-green.svg",class:"moins"%></span>
        </div>
        <div class="accordion_content">
        </div>
      </div>


    </div><!-- Fin accordions_list -->

    <div class="actif_ctas">
      <p>Vous avez un projet ?</p>
      <div class="flex">
        <%= link_to "",class:"btn_devis" do %>
          <span>Demander un devis</span><%= image_tag "pictos/arrow-circle.svg"%>
        <% end %>
        <% if @actif.document.present? %>
          <%= link_to rails_blob_path(@actif.document, disposition: 'attachment'),class:"btn_download" do %>
            <span>Télécharger la fiche</span><%= image_tag "pictos/download.svg"%>
          <% end %>
        <% end %>
      </div>
    </div>

  </div>

</section>
<section data-controller="carousel">
  <div class="inside carousel-actifs-control">
    <%= image_tag "pictos/fiole-plante.svg",class:""%>
    <div class="control-carousel">
      <span data-carousel-target="left" data-action="click->carousel#clickLeft" class="carousel_arrow"><%= image_tag "pictos/carousel-left.svg", alt:"" %></span>
      <span data-carousel-target="right" data-action="click->carousel#clickRight" class="carousel_arrow"><%= image_tag "pictos/carousel-right.svg",alt:"" %></span>
    </div>
  </div>
  <div class="carousel_actifs">
    <ul class="flex list_cards_actif carousel" data-carousel-target="carousel">
      <% @actifs.each do |actif| %>
        <li class="card_carousel" data-carousel-target="card">
          <%= link_to actif_path(actif) do %>
            <div class="card_carousel_img">
              <%= image_tag actif.photos[0] if actif.photos[0].present? %>
            </div>
            <div class="card_carousel_description">
              <span class="actif_property">Propriété</span>
              <h2 class="card_actif_titre"><%= actif.name %></h2>
              <div class="card_actif_text">
                <p>Ingrédient cosmétique minceur & raffermissant</p>
                <span class="card_actif_btn">Découvrir<%= image_tag 'arrow-right.svg'%></span>
              </div>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
    <div class="carousel_points">
      <% @actifs.each do |actif| %>
        <% if @actifs.to_a.index(actif) == 0 %>
          <span class="carousel_point active" data-carousel-target="point"></span>
        <% else %>
          <span class="carousel_point" data-carousel-target="point"></span>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/actifs/update.html.erb
<h1>Actifs#update</h1>
<p>Find me in app/views/actifs/update.html.erb</p>