config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  get "/", to: redirect('/fr', status:301)
  # Defines the root path route ("/")
  # root "posts#index"

  scope "/backoff" do
    #get "/", to: "admin#home"
    resources :admins, only: [:index], path:"/"
    resources :actifs, only: [:new,:create,:edit,:update,:destroy], as: :actif_backoff
    get "actifs", to: "admins#actifs", as: :actifs_backoff
    resources :articles, only: [:new,:create,:edit,:update,:destroy]
    resources :prestations, only: [:new, :create,:edit,:update,:destroy]
    resources :faqs, except:[:index],path: :faq
  end

  scope "/:locale" do
    root "pages#home"
    get "about", to: "pages#about"
    resources :actifs, only:[:index,:show]
    resources :authors,path:"/experts"
    get "blog", to: "articles#index"
    get "blog/:id", to: "articles#show", as: :post
    get "blog/:slug_authors/:id", to: "articles#show", as: :post_author
    get "blog/:category", to: "articles#category", as: :blog_category
    post "blog/category_filter", to: "articles#category_filter", as: :blog_filter
    get "prestation/:id",to: "prestations#show", as: :prestation_show

     post "send", to: "pages#send_contact"

    #get "/actifs", controller: "actifs", action: "index"
    #get "/actifs/:id", controller: "actifs", action: "show"
    localized do
      get "laboratoire-plantes", to: "pages#laboratoire_plantes"
      get "analyse-recherche-developpement",to: "pages#analyses"
      get "laboratoire-cosmetologie",to: "pages#cosmetologie"
      get "actifs",to: "actifs#index",as: :actifs
      get "faqs",to: "faqs#index",as: :faqs
      get "authors",to: "authors#index",as: :authors
      get "contact",to: "pages#contact"
      #resources :actifs, only:[:index,:show]
    end
  end




end

app/views/shared/_footer.html.erb
<div id="footer">
  <footer>
    <nav>

      <div id="footer_logo">
        <%= image_tag "logo-feuille.svg"%>
        <%= image_tag "logo-text.svg"%>
      </div>

      <div class="col_footer 1">
        <address>Parc d'innovation de Strasbourg<br>
        300 boulevard Sébastien Brandt<br>
        67412 Illkirch
        </address>
        <a href="tel:+33368854841"><%= image_tag "tel.svg"%>03 68 85 48 41</a>
        <p><%= image_tag "mail.svg"%>Nous contacter</p>
      </div>


      <ul class="col_footer 2">
        <li><a href="#">Télécharger la brochure</a></li>
        <li><a href="#">Questions Fréquentes</a></li>
        <li><a href="#">Lexique (définitions)</a></li>
        <li><a href="#">Recrutement</a></li>
      </ul>
      <ul class="col_footer 3">
        <li><a href="#">Backoffice Phytodia</a></li>
        <li><a href="#">Backoffice client</a></li>
        <li><a href="#">Outils</a></li>
      </ul>
      <ul class="col_footer 4">
        <li>Mentions légales</li>
        <li>Politique de confidentialité</li>
        <li>Gestion des cookies</li>
        <li>Plan du site</li>
      </ul>
      <div class="made_in_france">
        <%= image_tag "made-in-france.svg"%>
      </div>
    </nav>
  </footer>
</div>

app/views/shared/_mega_menu.html.erb
<div class="mega_menu">
  <div class="container_menu">
    <div class="intro_menu">
      <div class="intro_menu_img">
        <%= image_tag "fiole-verte-labo.svg"%>
      </div>
      <div class="intro_menu_text">
        <h2>Laboratoire des plantes</h2>
        <p>Vous travaillez avec les plantes de près ou de loin ?<br>
        Experts de la plante au produit depuis plus de 15 ans, nous mettons nos connaissances et notre savoir-faire au service de votre projet.<br>
        Tirer le meilleur des plantes grâce à la science, telle est la raison d'être des Laboratoires Phytodia.
        </p>
      </div>
    </div>
    <div class="links_menu">
      <ul class="grid_links">
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Extraction végétale" %>
          <ul>
          <li>Développement actifs (cosmétique)/extrait végétal</li>
          <li>Identification d'une ressource alternative</li>
          <li>Amélioration du process d'extraction végétale de votre matière première</li>
          </ul>
        </li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_mega_menu_cosme.html.erb
<div class="mega_menu">
  <div class="container_menu">
    <div class="intro_menu">
      <div class="intro_menu_img">
        <%= image_tag "cosmetique-vert.svg"%>
      </div>
      <div class="intro_menu_text">
        <h2>Laboratoire Cosmetologie</h2>
        <p>Vous travaillez avec les plantes de près ou de loin ?<br>
        Experts de la plante au produit depuis plus de 15 ans, nous mettons nos connaissances et notre savoir-faire au service de votre projet.<br>
        Tirer le meilleur des plantes grâce à la science, telle est la raison d'être des Laboratoires Phytodia.
        </p>
        <div class="more_infos_menu">
          <%= image_tag "green-arrow-right.svg"%>
          <%= link_to "En savoir plus","", class:"" %>
        </div>
      </div>
    </div>
    <div class="links_menu">
      <ul class="grid_links">
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Extraction végétale" %>
          <ul class="under_links">
            <li>Développement actifs (cosmétique)/extrait végétal</li>
            <li>Identification d'une ressource alternative</li>
            <li>Amélioration du process d'extraction végétale de votre matière première</li>
          </ul>
        </li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_mega_menu_labo.html.erb
<div class="mega_menu">
  <div class="container_menu">
    <div class="intro_menu">
      <div class="intro_menu_img">
        <%= image_tag "matrice-verte.svg"%>
      </div>
      <div class="intro_menu_text">
        <h2>Analyses, Recherche & Développement</h2>
        <p>Vous travaillez avec les plantes de près ou de loin ?<br>
        Experts de la plante au produit depuis plus de 15 ans, nous mettons nos connaissances et notre savoir-faire au service de votre projet.<br>
        Tirer le meilleur des plantes grâce à la science, telle est la raison d'être des Laboratoires Phytodia.
        </p>
        <div class="more_infos_menu">
          <%= image_tag "green-arrow-right.svg"%>
          <%= link_to "En savoir plus","", class:"" %>
        </div>
      </div>
    </div>
    <div class="links_menu">
      <ul class="grid_links">
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Extraction végétale" %>
          <ul class="under_links">
          <li>Développement actifs (cosmétique)/extrait végétal</li>
          <li>Identification d'une ressource alternative</li>
          <li>Amélioration du process d'extraction végétale de votre matière première</li>
          </ul>
        </li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_mega_menu_plantes.html.erb
<div class="mega_menu">
  <div class="container_menu">
    <div class="intro_menu">
      <div class="intro_menu_img">
        <%= image_tag "fiole-verte-labo.svg"%>
      </div>
      <div class="intro_menu_text">
        <h2>Laboratoire des plantes</h2>
        <p>Vous travaillez avec les plantes de près ou de loin ?<br>
        Experts de la plante au produit depuis plus de 15 ans, nous mettons nos connaissances et notre savoir-faire au service de votre projet.<br>
        Tirer le meilleur des plantes grâce à la science, telle est la raison d'être des Laboratoires Phytodia.
        </p>
        <div class="more_infos_menu">
          <%= image_tag "green-arrow-right.svg"%>
          <%= link_to "En savoir plus", send("laboratoire_plantes_#{locale.to_s}_path") %>
        </div>
      </div>
    </div>
    <div class="links_menu">
      <ul class="grid_links">
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Extraction végétale" %>
          <ul class="under_links">
          <li>Développement actifs (cosmétique)/extrait végétal</li>
          <li>Identification d'une ressource alternative</li>
          <li>Amélioration du process d'extraction végétale de votre matière première</li>
          </ul>
        </li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
        <li><%= link_to "Analyse molécules végétales" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<div id="navbar">
  <nav>
  <ul class="list_primary_buttons_nav">
    <div class="primary_buttons_nav">
      <li id="logo_nav">
      <%= link_to root_path do %>
        <% if params[:action] == "home" %>
          <%= image_tag "logo-feuille.svg"%>
          <h1>
            <%= image_tag "logo-text.svg", alt:t('navbar.logo')%>
          </h1>
        <% else %>
          <%= image_tag "logo-feuille.svg",alt:"logo Phytodia"%>
          <%= image_tag "logo-text.svg",alt:'Phytodia'%>
        <% end %>
      <% end %>
      </li>
      <li class="dropdown_nav header_nav_link">
        <%= link_to "#" do %>
          <span><%= t('navbar.laboratoire_plantes_html') %></span>
          <%= image_tag "chevron-bas.svg" %>
        <% end %>
        <%= render "shared/mega_menu_plantes" %>
      </li>
      <li class="dropdown_nav header_nav_link">
        <%= link_to "#" do %>
          <span><%= t('navbar.laboratoire_analyses_html') %></span>
          <%= image_tag "chevron-bas.svg" %>
        <% end %>
        <%= render "shared/mega_menu_labo" %>
      </li>
      <li class="dropdown_nav header_nav_link">
        <%= link_to "#" do %>
          <span><%= t('navbar.laboratoire_cosmetologie_html') %></span>
          <%= image_tag "chevron-bas.svg" %>
        <% end %>
        <%= render "shared/mega_menu_cosme" %>
      </li>
      <li class="dropdown_nav header_nav_link">
        <%= link_to "" do %>
          <span><%= t('navbar.actifs')%></span>
          <%= image_tag "chevron-bas.svg" %>
        <% end %>
        <%= render "shared/mega_menu_cosme" %>
      </li>
    </div>
    <div class="second_buttons_nav">
      <li><%= link_to t('navbar.about'),"",class:"header_nav_link_secondary" %></li>
      <li><%= link_to t('navbar.blog'),blog_path,class:"header_nav_link_secondary" %></li>
      <div id="contact_and_langues">
        <li><%= link_to t('contact.btn_contact').upcase,send("contact_#{locale.to_s}_path" ), class:"btn_contact" %></li>
        <div id="selector_langues">
          <%= image_tag "globe.svg"%>
          <% @langues.each do |langue|%>
            <% if locale == langue %>
              <%= link_to langue.to_s.upcase, url_for(locale: langue),class:"current_langue" %>
            <% else %>
              <%= link_to langue.to_s.upcase, url_for(locale: langue) %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </ul>
  </nav>
  <div id="breadcrumb" class="inside">
    <% if params[:action] != "home" %>
      <%= link_to root_path do %>
        <%= image_tag "pictos/house.svg"%>
      <% end %>
      <%= image_tag "pictos/point.svg",class:"point_breadcrumb"%>
    <% end %>
    <%= render_breadcrumbs :separator => "<span class='breadcrumb_separator'>|</span>".html_safe %>
  </div>
</div>

app/views/shared/_navmobile.html.erb
<nav id="navmobile" data-controller="nav">
    <div id="header_mobile">
      <div id="logo_nav">
          <%= image_tag "logo-feuille.svg"%>
          <%= image_tag "logo-text.svg"%>
      </div>
      <div class="hamburger" id="hamburger-1" data-action="click->nav#toggle" data-nav-target="burger">
          <span class="line"></span>
          <span class="line"></span>
          <span class="line"></span>
        </div>
    </div>
    <ul id="mobile_menu_links" class="" data-nav-target="menu_mobile">
      <li>
        <%= link_to "" do %>
          <span>Laboratoire des plantes</span>
          <%= image_tag "chevron-right.svg"%>
        <% end %>
      </li>
      <li>
        <%= link_to "" do %>
          <span>Analyse, Recherche & Développement</span>
          <%= image_tag "chevron-right.svg"%>
        <% end %>
      </li>
      <li>
        <%= link_to "" do %>
          <span>Laboratoire Cosmétologie</span>
          <%= image_tag "chevron-right.svg"%>
        <% end %>
      </li>
      <li>
        <%= link_to "" do %>
          <span>Nos actifs et produits</span>
          <%= image_tag "chevron-right.svg"%>
        <% end %>
      </li>
      <hr>
      <li>A propos</li>
      <li>Blog</li>
      <li>
        <%= link_to "Nous contacter", "#", class:"btn_contact"%>
      </li>
    </ul>

</nav>

app/views/shared/_your_project.html.erb
<aside class="your_project">
  <div class="blur">
    <div class="blur_text">
      <h2>Parlez-nous de votre projet</h2>
      <p>Faites confiance à notre savoir-faire pour transformer vos projets en succès</p>
    </div>
    <div>
      <a href="#" class="btn_contact white">Prenez contact</a>
    </div>
  </div>
</aside>